; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = src
include_dir = src
default_envs = teensy41

[env:teensy41]
platform = teensy@4.18.0
board = teensy41
framework = arduino
monitor_speed = 250000
lib_archive = no
lib_ignore = LittleFS
lib_deps = 
	https://github.com/grblHAL/uSDFS
	adafruit/Adafruit GFX Library
build_flags = 
	-g3
	-fmax-errors=5
	-DUSB_DUAL_SERIAL
	-DOVERRIDE_MY_MACHINE
	-include src/board/board_config.h
	-Isrc
	-Isrc/grblhal/core
	-Isrc/grblhal/driver
	-Isrc/grblhal/driver/boards
	-Isrc/grblhal/driver/peripherals
	-Isrc/grblhal/driver/streams
	-Isrc/grblhal/driver/storage
	-Isrc/grblhal/driver/storage/sdcard
	-Isrc/grblhal/driver/storage/littlefs
	-Isrc/grblhal/driver/network
	-Isrc/grblhal/driver/leds
